### ISSUE TITLE
Validations

### ISSUE THREAD

**Issue by palaparthi** [StrictlySkyler/instawork#2]
Hi,
Currently when I create a user with duplicate email I get a generic 400 error. Can you please fix this and any other validations with user friendly messages?

<img width="1512" alt="Screenshot 2024-12-12 at 11 35 50 PM" src="https://github.com/user-attachments/assets/59ef18cb-8eff-431f-8fea-d710f3369501" />

**Comment by strictlyskyler** [comment]
Hi @palaparthi, thanks for this.  I've just pushed some changes which address this.  Please have a look at your convenience.

Thanks!
